/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#fbfdf9",
        "background": "#fbfdf9",
        "secondary-container": "#dcfce7",
        "primary-container": "#15803d",
        "on-primary-fixed-variant": "#14532d",
        "on-primary-fixed": "#052e16",
        "on-surface-variant": "#3e4d3f",
        "surface-container-highest": "#d6e3cd",
        "tertiary-container": "#fef3c7",
        "on-secondary-fixed": "#052e16",
        "outline": "#70826f",
        "on-error-container": "#93000a",
        "inverse-primary": "#86efac",
        "on-tertiary-fixed-variant": "#78350f",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#bbf7d0",
        "on-tertiary-fixed": "#451a03",
        "surface-dim": "#dce6d8",
        "surface-container-low": "#f4f7f2",
        "primary-fixed-dim": "#86efac",
        "outline-variant": "#d1ded0",
        "error-container": "#fee2e2",
        "tertiary-fixed": "#fde68a",
        "inverse-on-surface": "#f0fdf4",
        "on-secondary-container": "#14532d",
        "primary-fixed": "#bbf7d0",
        "on-background": "#141f15",
        "on-primary": "#ffffff",
        "inverse-surface": "#1b281c",
        "error": "#dc2626",
        "surface-tint": "#16a34a",
        "tertiary": "#d97706",
        "on-primary-container": "#dcfce7",
        "secondary": "#166534",
        "surface-container": "#ebf1e8",
        "surface-container-high": "#e2ebd9",
        "surface": "#fbfdf9",
        "on-tertiary-container": "#78350f",
        "on-surface": "#141f15",
        "on-secondary-fixed-variant": "#166534",
        "tertiary-fixed-dim": "#fcd34d",
        "primary": "#15803d",
        "secondary-fixed-dim": "#86efac",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e2ebd9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(15px)" },
          "100%": { opacity: "1", transform: "translateY(0)" }
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" }
        }
      },
      animation: {
        "fade-in-up": "fade-in-up 0.5s ease-out forwards",
        "fade-in": "fade-in 0.3s ease-out forwards"
      },
      spacing: {
        xl: "80px",
        xs: "4px",
        base: "8px",
        sm: "12px",
        "container-max": "1280px",
        gutter: "24px",
        md: "24px",
        lg: "48px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "display-lg-mobile": ["Poppins"],
        "label-md": ["Poppins"],
        "headline-md": ["Poppins"],
        "headline-md-mobile": ["Poppins"],
        "body-lg": ["Poppins"],
        "label-sm": ["Poppins"],
        "title-lg": ["Poppins"],
        "body-md": ["Poppins"],
        "display-lg": ["Poppins"],
      },
      fontSize: {
        "display-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.2", letterSpacing: "0.01em", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-md-mobile": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", fontWeight: "600" }],
        "title-lg": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
};
